Added methods to the smart contract and tests. Added method to chainC…
DavidZamanian/Bachelor-thesis-blockchain-for-medical-records pull request #103
Opened 2022-05-08 07:52 UTC by Edenia97

Method to get the institution a medical personnel works at. The duplicate can be removed from firebase

2022-05-08 08:04 UTC, Chrimle commented on client/src/chainConnection/chainConnection.js
> -   * @returns {Promise<boolean>} true iff the invoker is permissioned by the given patient.
iff means "if and only if"

2022-05-08 17:50 UTC, Chrimle commented on contracts/Block4EHR.sol
> +    mapping(string => MedicalPersonnel) IdToMedicalPersonnel;
head's up; the variable-name doesn't start with a lower-case letter.

2022-05-08 17:51 UTC, Chrimle commented on truffle_test/test/testBlock4EHR.js
> +        it("getHealthCareInstitution fails given a valid medical personel ", async function () {
I don't understand this test case.

2022-05-08 17:52 UTC, Chrimle approved these changes
OK. Have a look at the comments

2022-05-09 07:21 UTC, hjernkrook commented on client/src/chainConnection/chainConnection.js
> -   * @returns {Promise<boolean>} true iff the invoker is permissioned by the given patient.
yeah, it was meant to say that, but 'if' works as well. I don't care which of them it says.

2022-05-09 07:22 UTC, hjernkrook commented on client/src/chainConnection/chainConnection.js
> +  async getHealthCareInstitution(MedicalPersonnelId){
variable names should start with lowercase letters

2022-05-09 07:25 UTC, hjernkrook commented on client/src/chainConnection/chainConnection.js
> +   * @returns {HealthcareInst} The instituion object the given medical personell works at.
incorrect return type. Should be Promise<Object>. HealthcareInst is not a datatype except in the contract. 
Also: the JSDoc should probably explain what attributes that the returned object has (i.e. id, name, region (:Object with its own attributes)  – if I'm not missing anything).

2022-05-09 07:27 UTC, hjernkrook commented on contracts/Block4EHR.sol
> +    mapping(string => MedicalPersonnel) IdToMedicalPersonnel;
Yeah, this should be `idToMedicalPersonnel`. Also: the `// ===== MEDICAL PERSONNEL MAPPINGS ======` at line 62 is redundant right? This mapping should be in the same section as `medicalPersonnels`.

2022-05-09 07:28 UTC, hjernkrook commented on contracts/Block4EHR.sol
> +    //======= GETTING THE HELTH CARE INSTITUTION A GIVEN MEDICAL PERSONNEL WORKS AT ========
*HEALTHCARE

2022-05-09 07:31 UTC, hjernkrook commented on truffle_test/test/testBlock4EHR.js
> +    describe("getHealthCareInstitution returns the Healthcare Institutions the given medicall personnel works at", function (){
* Healthcare Institution (there is only one)
*medical

2022-05-09 07:35 UTC, hjernkrook commented on truffle_test/test/testBlock4EHR.js
> +        it("getHealthCareInstitution fails given a valid medical personel ", async function () {
Me neither. I understand this as really just the same as the above test case, but checking that the id is not something that it shouldn't be, instead of checking it against what it should be. It's really just the same test case, and does not really say if the method returned the right thing or not, just that it didn't return one of the multiple wrong results. If possible, it would be better to test what is returned if you provide an invalid medical personnel's id. Is it null then, maybe?

2022-05-09 07:38 UTC, hjernkrook requested changes
The comments left here (except Chris' "iff"-comment) should be fixed before this is approved and merged. The most important is the return type and the test case, but since changed will be made, I commented on minor things as well, to keep good code quality.

2022-05-09 09:47 UTC, hjernkrook approved these changes
OK

2022-05-09 12:37 UTC, merged